### ISSUE TITLE
Another one.

### ISSUE THREAD

**Issue by SnHxFirefighter** [TayMcKenzieNZ/WallFixes#1]
Not really a issue but a "suggestion" 

https://www.gta5-mods.com/maps/better-braddock-pass-highway-ymap

**Comment by TayMcKenzieNZ** [comment]
Thanks! I tried to get this to work in FiveM previously but must have been doing something wrong, probably due to them being custom props or something. I'll try and figure it out 😛

**Comment by TayMcKenzieNZ** [comment]
Added!
